name: onemoreplace2go
favicon: null
layout_spectrum: 0.8324648935813457
typography_spectrum: 0.32568719843402505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.30422464525327086
  lightness: 0.07663688878528774
  saturation: 0.7160942603368312
  rhythmicContrast: 0.9382811323739588
purpose: []
